name: Build || Push || Deploy Cloud 

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-east1

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/122809017192/locations/global/workloadIdentityPools/gde-kj-linebot/providers/github-provider
        service_account: ${{ secrets.GCP_SA_EMAIL }}
        
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'      
