name: Build || Push || Deploy Cloud 

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  REGION: asia-east1
  POOL: gde-kj-linebot
  PROVIDER: github-provider


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Docker image tag
      id: set_tag
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}

    # - id: 'auth'
    #   uses: google-github-actions/auth@v2
    #   with:
    #     workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ env.POOL }}/providers/${{ env.PROVIDER }}
    #     service_account: ${{ secrets.GCP_SA_EMAIL }}
        
    # - name: 'Set up Cloud SDK'
    #   uses: 'google-github-actions/setup-gcloud@v2'

    # - name: 'Use gcloud CLI'
    #   run: 'gcloud info'      
